import ncseBanner from '../assets/thanks/ncse-banner.png';
import warpBanner from '../assets/thanks/warp-banner.png';

const contributorImageUrl = (perRow: number) =>
    `https://gthanks.yorukot.me/image?target=yorukot&include_bots=false&per_row=${perRow}&shape=square&limit=1000`;

const contributorsImage = contributorImageUrl(20);
const contributorsImageLaptop = contributorImageUrl(16);
const contributorsImageTablet = contributorImageUrl(12);
const contributorsImageMobile = contributorImageUrl(8);

export const thanks = {
    hero: {
        eyebrow: '/thanks',
        titleLines: ['Back the work.', 'Fund the next build.'],
        description:
            'This page is for the people and teams who keep open-source tools, articles, and late-night shipping sessions alive.',
    },
    sponsorNote: {
        text: "If you've donated or helped support my work in any way, feel free to email me and I'll add you to this page.",
        emailLabel: 'hi@yorukot.me',
        href: 'mailto:hi@yorukot.me',
    },
    donationOptions: [
        {
            label: 'SPONSORS',
            title: 'Send a direct thank you',
            href: 'https://yorukot.me/sponsor',
            action: 'Donation',
            description: '',
        },
        {
            label: 'Company',
            title: 'Sponsor as a team or brand',
            href: 'mailto:hi@yorukot.me',
            action: 'Start a conversation',
            description: '',
        },
    ],
    sponsorTiers: [
        {
            tier: 'Sponsors',
            sponsors: [
                {
                    name: 'Warp',
                    href: 'https://www.warp.dev/?utm_source=github&utm_medium=referral&utm_campaign=superfile',
                    note: 'Sponsors superfile and helps keep its development moving.',
                    banner: {
                        src: warpBanner,
                        alt: 'Warp sponsor banner',
                    },
                },
            ],
        },
    ],
    specialThanks: [
        {
            title: 'NCSE',
            href: 'https://www.ncse.tw/en/',
            description: 'Special thanks for providing a free VPS that helps power the project infrastructure.',
            banner: {
                src: ncseBanner,
                alt: 'NCSE special thanks banner',
            },
        },
    ],
    contributors: {
        description: 'Thank you to every contributor whose work helps move my projects forward.',
        image: {
            src: contributorsImage,
            laptopSrc: contributorsImageLaptop,
            tabletSrc: contributorsImageTablet,
            mobileSrc: contributorsImageMobile,
            alt: 'Yorukot contributor image generated by GThanks',
        },
    },
} as const;
